### PR TITLE
Update calendar_sources.txt

### PR DESCRIPTION
**Pull request by mdziel**
Add Future of Financial Information (FutFinInfo) Webinar series dates for Fall 2020

### CODE REVIEW

**Comment by just-cameron** [comment]
Awesome, thanks!

**Comment by mdziel** [comment]
Well, thank you, sir!

**Comment by mdziel** [comment]
When should the dates start to show up in the main calendar? Asking from the standpoint of making sure it works :)

**Comment by just-cameron** [comment]
It's already done, at least for the calendar file: https://github.com/cpfiffer/virtual-econ.info/blob/master/virtual-econ-calendar.ics

It'll show up on the website and Google calendar a little later because Google is slow.

**Comment by just-cameron** [comment]
By "a little later" I mean possibly as long as a day.

**Comment by mdziel** [comment]
Ok, got it – thanks a lot!

**Pull request merged**
