### PR TITLE
Adding in the ics stuff

### PR DESCRIPTION
**Pull request by michaelewens**
We need to work on the readme (e.g. tell people to create a calendar, then add to sources).  Not sure that the Github action is setup.  If it needs an external server running a cron, then I can do that with one my linode servers.  

My view about the readme: 

- tell people to add their seminar info
- tell them to go to 'sources.txt' in the folder and add their "public url" from their calendar
- provide some suggestions for calendar format

### CODE REVIEW

**Comment by michaelewens** [comment]
Thanks, I will work on getting it running now.

**Comment by just-cameron** [comment]
Oh, don't worry about it. I'm most of the way there now. Fixed a bunch of bugs and have it mostly humming along.

**Comment by michaelewens** [comment]
That buggy?   Sorry.  For the sources file...I will remove from that calendar all the redundant ones that have their own independent calendars.  The one that we maintain can be for those that don't have their own ICS (could email organizers with instructions on creating one).  Ideally, the master calendar == the out.ics created with this script + cron.

**Comment by just-cameron** [comment]
Yeah, sounds good. By the way, I changed `out.ics` to `virtual-econ-calendar.ics` so it's a bit more informative.

**Pull request merged**
