### PR TITLE
Update seminars.md

### PR DESCRIPTION
**Pull request by jessicasuzanne**

### CODE REVIEW

**Comment by jessicasuzanne** [comment]
Hi -- trying to add information on the Labor & Finance Online Seminar. Sorry, new to this, and not sure how to update.

**Comment by just-cameron** [comment]
Oh, like you want to add additional information? You can do this by

1. Go to the "Files changed" tab
2. On the right hand side of the screen, underneath a big green button "Review changes", you should see three dots. Click this and select "Edit file".

If that's not what you wanted and this is correct, I'm happy to merge this in.

**Comment by jessicasuzanne** [comment]
No sorry I wasn't clear. I did add information, under the new "Labor & Finance Online Seminar (LFOS)" section. I want to merge this in. Thank you!

**Comment by just-cameron** [comment]
My apologies for the misunderstanding, I'll merge this in. Thanks!

**Pull request merged**
